### ISSUE TITLE
Crash when right-clicking any block

### ISSUE THREAD

**Issue by aaronhowser1** [AlmostReliable/summoningrituals-forge#3] opened 2022-09-23 09:31 UTC
### Version

summoningrituals-1.18.2-1.1.0

### Describe the bug!

Some items, when used, cause the game to crash to desktop.

These items aren't from this mod. The Emperor's Chalice from Reliquary, as well as the Fridge from Cooking for Blockheads, resulted in the crash.

The crash report mentions the industrictible altar, which has not been placed anywhere.

[Crash report 1](https://gist.github.com/eb4388d1d72492c60ae0479d8746bfe8)
[Crash report 2](https://gist.github.com/3fdd99623f94726ee16af72db8cd06a8)
[Crash report 3](https://gist.github.com/8d9500fba0b3bbf813a29e9048b1a889)

### Crash Report

Above

### Log

https://gist.github.com/9fbb0647561ea893a28d1617f4117178

### Additional Context

Yes

### Modifications

Too many to list

### Did the issue happen in singleplayer or on a server?

Server

**Comment by aaronhowser1** [comment] 2022-09-23 10:03
Looks like it happens when I right click any block?

**Comment by rlnt** [comment] 2022-09-24 16:58
I can not reproduce this. According to this line in your logs:
```
[net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
```
it looks like you are playing on a dedicated server. If so, my only guess would be that your server still has an older mod version that doesn't have the Indestructible Altar yet while your client is using the current version.

The main issue according to your logs is:
```
Registry Object not present: summoningrituals:indestructible_altar
```
which is quite interesting since it's able to find the normal altar without any issues.

**Comment by aaronhowser1** [comment] 2022-09-25 23:18
Turns out the server hadn't updated the mod. I haven't had the chance to test since it has, but that's probably the issue

**Comment by rlnt** [comment] 2022-10-01 22:05
I am going to close this since there was no further report and the mod seems to work really well in the recently released FTB Inferno pack. If you are still having issues, let me know.

**Closed as not planned** 2022-10-01 22:06 UTC
Labels: type: bug, state: can't reproduce
